{ paths ? "/", crawlDelay ? "2" }:
{
  pre_comment = ''
    AI bots

    Sourced from:
    - https://www.vg.no/robots.txt
    - https://codeberg.org/robots.txt
    - https://github.com/ai-robots-txt/ai.robots.txt/blob/main/robots.txt
  '';

  Disallow = paths;
  Crawl-delay = crawlDelay;

  User-agent = [
    "AI2Bot"
    "AI2Bot-DeepResearchEval"
    "AIWebIndex"
    "AddSearchBot"
    "AgentTimes"
    "Ai2Bot-Dolma"
    "AmazonBuyForMe"
    "Amazonbot"
    "Amzn-SearchBot"
    "Amzn-User"
    "Andibot"
    "Anomura"
    "ApifyBot"
    "ApifyWebsiteContentCrawler"
    "Applebot"
    "Applebot-Extended"
    "Aranet-SearchBot"
    "Awario"
    "AzureAI-SearchBot"
    "Bravebot"
    "Brightbot 1.0"
    "Brightbot"
    "BuddyBot"
    "Bytespider"
    "CCBot"
    "Channel3Bot"
    "ChatGLM-Spider"
    "ChatGPT Agent"
    "ChatGPT-User"
    "Claude-Code"
    "Claude-SearchBot"
    "Claude-User"
    "Claude-Web"
    "ClaudeBot"
    "CloudVertexBot"
    "Cloudflare-AutoRAG"
    "Code"
    "Cotoyogi"
    "CragCrawler"
    "Crawl4AI"
    "Crawlspace"
    "Cursor"
    "Datenbank Crawler"
    "DeepSeekBot"
    "Devin"
    "Diffbot"
    "Diffbot-User"
    "DoubaoBot"
    "DuckAssistBot"
    "ERNIEBot"
    "Echobot Bot"
    "EchoboxBot"
    "ExaBot"
    "ExaSearchBot"
    "FacebookBot"
    "Factset_spyderbot"
    "FirecrawlAgent"
    "FriendlyCrawler"
    "GPTBot"
    "GeistHaus-PageFetcher"
    "Gemini-Deep-Research"
    "Google-Agent"
    "Google-CloudVertexBot"
    "Google-Extended"
    "Google-Firebase"
    "Google-Gemini-CLI"
    "Google-NotebookLM"
    "GoogleAgent-Mariner"
    "GoogleAgent-URLContext"
    "GoogleOther"
    "GoogleOther-Image"
    "GoogleOther-Video"
    "HenkBot"
    "ICC-Crawler"
    "ISSCyberRiskCrawler"
    "ImagesiftBot"
    "Kangaroo Bot"
    "Kimi-SearchBot"
    "Kimi-User"
    "KimiBot"
    "KlaviyoAIBot"
    "KunatoCrawler"
    "LAIONDownloader"
    "LCC"
    "Lightpanda"
    "LinerBot"
    "Linguee Bot"
    "LinkupBot"
    "Manus-User"
    "Meta-ExternalAgent"
    "Meta-ExternalFetcher"
    "MistralAI-Index"
    "MistralAI-Training"
    "MistralAI-User"
    "MistralAI-User/1.0"
    "Mozilla-Tabstack"
    "MyCentralAIScraperBot"
    "NagetBot"
    "NotebookLM"
    "NovaAct"
    "OAI-AdsBot"
    "OAI-SearchBot"
    "Omgili"
    "Omgilibot"
    "OpenAI"
    "Operator"
    "PanguBot"
    "Panscient"
    "Perplexity-User"
    "PerplexityBot"
    "PetalBot"
    "PhindBot"
    "Poggio-Citations"
    "Poseidon Research Crawler"
    "QualifiedBot"
    "Querit-SearchBot"
    "QueritBot"
    "QuillBot"
    "QwenBot"
    "Reflectionbot"
    "SBIntuitionsBot"
    "Scrapy"
    "SemrushBot-OCOB"
    "SemrushBot-SWA"
    "Shap-User"
    "ShapBot"
    "Sidetrade indexer bot"
    "Spider"
    "TavilyBot"
    "Terra Cotta"
    "TerraCotta"
    "Thinkbot"
    "TikTokSpider"
    "Timpibot"
    "TongyiBot"
    "Trae"
    "TwinAgent"
    "UseAI"
    "VelenPublicWebCrawler"
    "WARDBot"
    "WRTNBot"
    "Webzio-Extended"
    "YaK"
    "YandexAdditional"
    "YandexAdditionalBot"
    "YiyanBot"
    "YouBot"
    "ZanistaBot"
    "aiHitBot"
    "amazon-QBusiness"
    "amazon-kendra"
    "anthropic-ai"
    "atlassian-bot"
    "bedrockbot"
    "bigsur.ai"
    "cohere-ai"
    "cohere-training-data-crawler"
    "facebookexternalhit"
    "iAskBot"
    "iaskspider"
    "iaskspider/2.0"
    "imageSpider"
    "img2dataset"
    "kagi-fetcher"
    "laion-huggingface-processor"
    "meta-externalagent"
    "meta-externalfetcher"
    "meta-webindexer"
    "netEstate Imprint Crawler"
    "newsai"
    "omgili"
    "omgilibot"
    "opencode"
    "panscient.com"
    "quillbot.com"
    "webzio-extended"
    "wpbot"
  ];
}
