name: "Eval nix flake"
on:
  pull_request:
  push:
jobs:
  evals:
    runs-on: debian-latest
    steps:
    - name: Install sudo
      run: apt-get install --update --assume-yes sudo

    - uses: actions/checkout@v6

    - uses: https://github.com/cachix/install-nix-action@v31

    - run: nix flake check
