{
 "title": "Synapse",
 "tags": [ "matrix" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "bucket_size", "label": "Bucket Size", "query": "30s,1m,2m,5m,10m,15m" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds_total, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds_total, job)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds_total, index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Event Send Time (excluding errors, all workers)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Event Send Time Quantiles (excluding errors, all workers)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.05, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "sum(rate(synapse_http_server_response_time_seconds_sum{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) / sum(rate(synapse_http_server_response_time_seconds_count{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size]))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum(rate(synapse_storage_events_persisted_events_total{instance=\"$instance\"}[$bucket_size]))",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "downsampler": "max",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "$bucket_size"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
     "legendFormat": "{{job}} {{index}}"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
     "legendFormat": "{{job}}-{{index}}"
    }
   ]
  },
  {
   "title": "Process info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_system_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} system "
      },
      {
       "expr": "rate(process_cpu_user_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} user"
      }
     ]
    },
    {
     "title": "Reactor tick quantiles",
     "type": "timeseries",
     "description": "Shows the time in which the given percentage of reactor ticks completed, over the sampled timespan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 99.9%"
      },
      {
       "expr": "histogram_quantile(0.99, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 90%"
      },
      {
       "expr": "rate(python_twisted_reactor_tick_time_sum{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]) / rate(python_twisted_reactor_tick_time_count{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} mean"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}} {{index}}"
      },
      {
       "expr": "sum(process_resident_memory_bytes{instance=\"$instance\",job=~\"$job\",index=~\"$index\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Prometheus scrape time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "scrape_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Up",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min_over_time(up{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Stacked CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_response_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_response_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      },
      {
       "expr": "rate(synapse_background_process_ru_utime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_background_process_ru_stime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP request rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_client_requests_total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}}"
      },
      {
       "expr": "rate(synapse_http_matrixfederationclient_requests_total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} (federation)"
      }
     ]
    },
    {
     "title": "Threadpool activity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "synapse_threadpool_working_threads{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Event Send Time (Including errors, across all workers)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\"}[$bucket_size])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events Persisted (all workers)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_persisted_events_total{instance=\"$instance\"}[$bucket_size])) without (job,index)"
      }
     ]
    },
    {
     "title": "Events/s Local vs Remote",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_source_type{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events/s by Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_event_type{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events/s by Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_origin{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{origin_entity}} ({{origin_type}})"
      }
     ]
    },
    {
     "title": "Memberships/s by Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_persisted_events_sep_total{job=~\"$job\",index=~\"$index\", type=\"m.room.member\",instance=\"$instance\", origin_type=\"local\"}[$bucket_size])) by (origin_type, origin_entity)",
       "legendFormat": "{{origin_entity}} ({{origin_type}})"
      }
     ]
    },
    {
     "title": "Event send time quantiles by worker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 50%"
      },
      {
       "expr": "sum(rate(synapse_http_server_response_time_seconds_sum{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method) / sum(rate(synapse_http_server_response_time_seconds_count{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method)",
       "legendFormat": "{{job}}-{{index}} mean"
      }
     ]
    },
    {
     "title": "Stateres worst-case",
     "type": "timeseries",
     "description": "CPU and DB time spent on most expensive state resolution in a room, summed over all workers. This is a very rough proxy for \"how fast is state res\", but it doesn't accurately represent the system load (e.g. it completely ignores cheap state resolutions).\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s/s" } },
     "targets": [
      {
       "expr": "sum(rate(synapse_state_res_db_for_biggest_room_seconds_total{instance=\"$instance\"}[1m]))",
       "legendFormat": "DB time"
      },
      {
       "expr": "sum(rate(synapse_state_res_cpu_for_biggest_room_seconds_total{instance=\"$instance\"}[1m]))",
       "legendFormat": "CPU time"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Count by arrival time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_requests_received_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Top 10 Request Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_requests_received_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\",method!=\"OPTIONS\"}[$bucket_size]) and topk(10,synapse_http_server_requests_received_total{instance=\"$instance\",job=~\"$job\",method!=\"OPTIONS\"})",
       "legendFormat": "{{method}} {{servlet}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Total CPU Usage by Endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_in_flight_requests_ru_utime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_in_flight_requests_ru_stime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Average CPU Usage by Endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(synapse_http_server_in_flight_requests_ru_utime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_in_flight_requests_ru_stime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) / rate(synapse_http_server_requests_received_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "DB Usage by endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_in_flight_requests_db_txn_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Non-sync avg response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(synapse_http_server_response_time_seconds_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\",tag!=\"incremental_sync\"}[$bucket_size])) without (code))/(sum(rate(synapse_http_server_response_time_seconds_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\",tag!=\"incremental_sync\"}[$bucket_size])) without (code))",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}}"
      }
     ]
    },
    {
     "title": "Requests in flight",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,synapse_http_server_in_flight_requests_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"})",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}}"
      },
      {
       "expr": "sum(avg_over_time(synapse_http_server_in_flight_requests_count{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Background jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage by background jobs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_ru_utime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_background_process_ru_stime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "DB usage by background jobs (including scheduling time)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_db_txn_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) +  rate(synapse_background_process_db_sched_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Background jobs in flight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_background_process_in_flight_count{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Federation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Outgoing federation transaction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_client_sent_transactions_total{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "successful txn rate"
      },
      {
       "expr": "sum(rate(synapse_util_metrics_block_count_total{block_name=\"_send_new_transaction\",instance=\"$instance\"}[$bucket_size]) - ignoring (block_name) rate(synapse_federation_client_sent_transactions_total{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "failed txn rate"
      }
     ]
    },
    {
     "title": "Incoming PDU/EDU rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_server_received_pdus_total{instance=~\"$instance\"}[$bucket_size]))",
       "legendFormat": "pdus"
      },
      {
       "expr": "sum(rate(synapse_federation_server_received_edus_total{instance=~\"$instance\"}[$bucket_size]))",
       "legendFormat": "edus"
      }
     ]
    },
    {
     "title": "Outgoing PDU/EDU rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_client_sent_pdu_destinations:total_total{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "pdus"
      },
      {
       "expr": "sum(rate(synapse_federation_client_sent_edus_total{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "edus"
      }
     ]
    },
    {
     "title": "Outgoing EDUs by type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_federation_client_sent_edus_by_type_total{instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "In-memory federation transmission queues",
     "type": "graph",
     "description": "The number of events in the in-memory queues ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short", "label": "events" }
     ],
     "targets": [
      {
       "expr": "synapse_federation_transaction_queue_pending_pdus{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "pending PDUs {{job}}-{{index}}"
      },
      {
       "expr": "synapse_federation_transaction_queue_pending_edus{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "pending EDUs {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Outgoing EDU queues on master",
     "type": "graph",
     "description": "Number of events queued up on the master process for processing by the federation sender",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "synapse_federation_send_queue_presence_changed_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "presence changed"
      },
      {
       "expr": "synapse_federation_send_queue_presence_map_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "presence map"
      },
      {
       "expr": "synapse_federation_send_queue_presence_destinations_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "presence destinations"
      },
      {
       "expr": "synapse_federation_send_queue_keyed_edu_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "keyed edus"
      },
      {
       "expr": "synapse_federation_send_queue_edus_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "other edus"
      },
      {
       "expr": "synapse_federation_send_queue_pos_time_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "stream positions"
      }
     ]
    },
    {
     "title": "Federation send PDU lag",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "sum(rate(synapse_event_processing_lag_by_event_bucket{instance=\"$instance\",name=\"federation_sender\"}[$bucket_size])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Federation send PDU lag quantiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "25%"
      },
      {
       "expr": "histogram_quantile(0.05, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "5%"
      },
      {
       "expr": "sum(rate(synapse_event_processing_lag_by_event_sum{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) / sum(rate(synapse_event_processing_lag_by_event_count{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Handle inbound PDU time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_server_pdu_process_time_bucket{instance=\"$instance\"}[$bucket_size])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Age of oldest event in staging area",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "synapse_federation_server_oldest_inbound_pdu_in_staging{job=\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "rss {{index}}"
      }
     ]
    },
    {
     "title": "Number of events in federation staging area",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "synapse_federation_server_number_inbound_pdu_in_staging{job=\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "rss {{index}}"
      }
     ]
    },
    {
     "title": "Soft-failed event rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_soft_failed_events_total{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "soft-failed events"
      }
     ]
    }
   ]
  },
  {
   "title": "Federation rate limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of rate limit rejected requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(synapse_rate_limit_reject_total{instance=\"$instance\"}[$bucket_size]))"
      }
     ]
    },
    {
     "title": "Number of requests being slept by the rate limiter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(synapse_rate_limit_sleep_total{instance=\"$instance\"}[$bucket_size]))"
      }
     ]
    },
    {
     "title": "Number of hosts being rejected by the rate limiter",
     "type": "timeseries",
     "description": "Why is the data zero (0)? https://github.com/matrix-org/synapse/pull/13541#discussion_r951926322",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(increase(synapse_rate_limit_reject_affected_hosts{instance=\"$instance\"}[$bucket_size]))"
      }
     ]
    },
    {
     "title": "Number of hosts being slept by the rate limiter",
     "type": "timeseries",
     "description": "https://github.com/matrix-org/synapse/pull/13541",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(increase(synapse_rate_limit_sleep_affected_hosts{instance=\"$instance\"}[$bucket_size]))"
      }
     ]
    },
    {
     "title": "Rate limit queue wait time Quantiles (all workers)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9995, sum(rate(synapse_rate_limit_queue_wait_time_seconds_bucket{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": ">99%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(synapse_rate_limit_queue_wait_time_seconds_bucket{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(synapse_rate_limit_queue_wait_time_seconds_bucket{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(synapse_rate_limit_queue_wait_time_seconds_bucket{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(synapse_rate_limit_queue_wait_time_seconds_bucket{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(synapse_rate_limit_queue_wait_time_seconds_bucket{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "25%"
      },
      {
       "expr": "histogram_quantile(0.05, sum(rate(synapse_rate_limit_queue_wait_time_seconds_bucket{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "5%"
      },
      {
       "expr": "sum(rate(synapse_rate_limit_queue_wait_time_seconds_sum{index=~\"$index\",instance=\"$instance\"}[$bucket_size])) / sum(rate(synapse_rate_limit_queue_wait_time_seconds_count{index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Rate of requests being slept by the rate limiter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "sum(rate(synapse_rate_limit_sleep_total{instance=\"$instance\"}[$bucket_size]))"
      },
      {
       "expr": "50",
       "legendFormat": "Default reject threshold (50 requests within a second)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pushes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Push rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_httppusher_http_pushes_processed_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) and on (instance, job, index) (synapse_http_httppusher_http_pushes_failed_total + synapse_http_httppusher_http_pushes_processed_total) > 0",
       "legendFormat": "processed {{job}}"
      },
      {
       "expr": "rate(synapse_http_httppusher_http_pushes_failed_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) and on (instance, job, index) (synapse_http_httppusher_http_pushes_failed_total + synapse_http_httppusher_http_pushes_processed_total) > 0",
       "legendFormat": "failed {{job}}"
      }
     ]
    },
    {
     "title": "Active pusher instances by app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,synapse_pushers{job=~\"$job\",index=~\"$index\", instance=\"$instance\"})",
       "legendFormat": "{{kind}} {{app_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Push Rule Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Iterations over State",
     "type": "graph",
     "description": "How many entries in current state that we are iterating over while calculating push rules.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_push_bulk_push_rule_evaluator_push_rules_state_size_counter_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Push Rule Invalidations",
     "type": "graph",
     "description": "Rate that the cached push rules for a room get invalidated due to underlying push rules being changed. ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_push_bulk_push_rule_evaluator_push_rules_invalidation_counter_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Delta Optimisation",
     "type": "graph",
     "description": "How often the \"delta optimisation\" happens.\n\nThe delta optimisation is when we update the push rules for a room incrementally after a state change where we know the delta between the old state and the new state.\n\nThis can't happen if we don't the delta or we're calculating push rules from scratch.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_util_caches_cache_hits{job=\"$job\",index=~\"$index\",name=\"push_rules_delta_state_cache_metric\",instance=\"$instance\"}[$bucket_size]))/sum(rate(synapse_util_caches_cache{job=\"$job\",index=~\"$index\", name=\"push_rules_delta_state_cache_metric\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Hit Rate"
      },
      {
       "expr": "sum(rate(synapse_util_caches_cache{job=\"$job\",index=~\"$index\", name=\"push_rules_delta_state_cache_metric\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Number of calls"
      }
     ]
    },
    {
     "title": "How often we reuse existing calculated push rules",
     "type": "graph",
     "description": "How often we have the correct cached push rules for a room.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_util_caches_cache_hits{job=\"$job\",index=~\"$index\",name=\"room_push_rule_cache\",instance=\"$instance\"}[$bucket_size]))/sum(rate(synapse_util_caches_cache{job=\"$job\",index=~\"$index\", name=\"room_push_rule_cache\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Hit Rate"
      },
      {
       "expr": "sum(rate(synapse_util_caches_cache{job=\"$job\",index=~\"$index\", name=\"room_push_rule_cache\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Number of calls"
      }
     ]
    },
    {
     "title": "How often we have the RulesForRoom cached",
     "type": "graph",
     "description": "How often we have existing cached push rules for the room. \n\nNote that these might be outdated and need to be recalculated if the state has changed.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_util_caches_cache_hits{job=\"$job\",index=~\"$index\",name=\"_get_rules_for_room\",instance=\"$instance\"}[$bucket_size]))/sum(rate(synapse_util_caches_cache{job=\"$job\",index=~\"$index\", name=\"_get_rules_for_room\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Hit Rate"
      },
      {
       "expr": "sum(rate(synapse_util_caches_cache{job=\"$job\",index=~\"$index\", name=\"_get_rules_for_room\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Number of calls"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg time waiting for db conn",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(synapse_storage_schedule_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_schedule_time_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Db scheduling time quantiles",
     "type": "graph",
     "description": "Shows the time in which the given percentage of database queries were scheduled, over the sampled timespan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 90%"
      },
      {
       "expr": "rate(synapse_storage_schedule_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_schedule_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}} {{index}} mean"
      }
     ]
    },
    {
     "title": "Top DB transactions by txn rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(synapse_storage_transaction_time_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    },
    {
     "title": "DB transactions by total txn time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_transaction_time_sum_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    },
    {
     "title": "Average DB txn time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_transaction_time_sum_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_transaction_time_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    },
    {
     "title": "Time waiting for DB connection quantiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(synapse_storage_schedule_time_bucket{index=~\"$index\",instance=\"$instance\",job=\"$job\"}[$bucket_size])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(synapse_storage_schedule_time_bucket{index=~\"$index\",instance=\"$instance\",job=\"$job\"}[$bucket_size])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(synapse_storage_schedule_time_bucket{index=~\"$index\",instance=\"$instance\",job=\"$job\"}[$bucket_size])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(synapse_storage_schedule_time_bucket{index=~\"$index\",instance=\"$instance\",job=\"$job\"}[$bucket_size])) by (le))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-block metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total CPU Usage by Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_ru_utime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\",block_name!=\"wrapped_request_handler\"}[$bucket_size]) + rate(synapse_util_metrics_block_ru_stime_seconds_total[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average CPU Time per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(rate(synapse_util_metrics_block_ru_utime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) + rate(synapse_util_metrics_block_ru_stime_seconds_total[$bucket_size])) / rate(synapse_util_metrics_block_count_total[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Total DB Usage by Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Database Transaction time, by Block",
     "type": "graph",
     "description": "The time each database transaction takes to execute, on average, broken down by metrics block.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_db_txn_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Transactions per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_db_txn_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Wallclock Time per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_time_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Block count",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache_hits{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])/rate(synapse_util_caches_cache{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_util_caches_cache_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache request rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Top 10 cache misses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(synapse_util_caches_cache{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]) - rate(synapse_util_caches_cache_hits{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache eviction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "hertz", "label": "entries / second" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache_evicted_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{name}} ({{reason}}) {{job}}-{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Response cache size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_util_caches_response_cache_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Response cache hit rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_response_cache_hits{instance=\"$instance\", job=~\"$job\", index=~\"$index\"}[$bucket_size])/rate(synapse_util_caches_response_cache{instance=\"$instance\", job=~\"$job\", index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total GC time by bucket (10m smoothing)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[10m])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "Average GC Time Per Collection",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(python_gc_time_count[$bucket_size])",
       "legendFormat": "{{job}} {{index}} gen {{gen}} "
      }
     ]
    },
    {
     "title": "Allocation counts",
     "type": "graph",
     "description": "'gen 0' shows the number of objects allocated since the last gen0 GC.\n'gen 1' / 'gen 2' show the number of gen0/gen1 GCs since the last gen1/gen2 GC.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      {
       "format": "short",
       "label": "Gen N-1 GCs since last Gen N GC"
      }
     ],
     "targets": [
      {
       "expr": "python_gc_counts{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "Object counts per collection",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_unreachable_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(python_gc_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "GC frequency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "GC durations",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sum(rate(python_gc_time_bucket[$bucket_size])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate of outgoing commands",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum (rate(synapse_replication_tcp_protocol_outbound_commands_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (name, conn_id)",
       "legendFormat": "{{job}}-{{index}} {{command}}"
      }
     ]
    },
    {
     "title": "Rate of outgoing RDATA commands, by stream",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "rate(synapse_replication_tcp_resource_stream_updates_total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{stream_name}}"
      }
     ]
    },
    {
     "title": "Rate of incoming commands (including echoes)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "sum (rate(synapse_replication_tcp_protocol_inbound_commands_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (name, conn_id)",
       "legendFormat": "{{job}}-{{index}} {{command}}"
      }
     ]
    },
    {
     "title": "Rate of incoming RDATA commands (excluding echoes), by stream",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "rate(synapse_replication_tcp_protocol_inbound_rdata_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{stream_name}}"
      }
     ]
    },
    {
     "title": "Queued incoming RDATA commands, by stream",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_replication_tcp_command_queue{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{stream_name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Replication connection close reasons",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_replication_tcp_protocol_close_reason_total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{reason_type}}"
      }
     ]
    },
    {
     "title": "Replication connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_replication_tcp_resource_connections_per_stream{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} {{stream_name}}"
      },
      {
       "expr": "synapse_replication_tcp_resource_total_connections{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event processing loop positions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Event processing lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "events" }
     ],
     "targets": [
      {
       "expr": "max(synapse_event_persisted_position{instance=\"$instance\"}) - on() group_right() synapse_event_processing_positions{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Age of last processed event",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "time()*1000-synapse_event_processing_last_ts{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Event processing catchup rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      {
       "format": "none",
       "label": "fallbehind(-) / catchup(+):  s/sec"
      }
     ],
     "targets": [
      {
       "expr": "deriv(synapse_event_processing_last_ts{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/1000 - 1",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extremities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of rooms, by number of forward extremities in room",
     "type": "heatmap",
     "description": "Colour reflects the number of rooms with the given number of forward extremities, or fewer.\n\nThis is only updated once an hour.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "synapse_forward_extremities_bucket{instance=\"$instance\"} and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Room counts, by number of extremities",
     "type": "graph",
     "description": "Number of rooms with the given number of forward extremities or fewer.\n\nThis is only updated once an hour.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "none", "label": "Number of rooms" }
     ],
     "targets": [
      {
       "expr": "synapse_forward_extremities_bucket{instance=\"$instance\"} > 0",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events persisted, by number of forward extremities in room (heatmap)",
     "type": "heatmap",
     "description": "Colour reflects the number of events persisted to rooms with the given number of forward extremities, or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events persisted, by number of forward extremities in room (quantiles)",
     "type": "graph",
     "description": "For a given percentage P, the number X where P% of events were persisted to rooms with X forward extremities or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Number of extremities in room" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.75, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Events persisted, by number of stale forward extremities in room (heatmap)",
     "type": "heatmap",
     "description": "Colour reflects the number of events persisted to rooms with the given number of stale forward extremities, or fewer.\n\nStale forward extremities are those that were in the previous set of extremities as well as the new.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events persisted, by number of stale forward extremities in room (quantiles)",
     "type": "graph",
     "description": "For  given percentage P, the number X where P% of events were persisted to rooms with X stale forward extremities or fewer.\n\nStale forward extremities are those that were in the previous set of extremities as well as the new.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      {
       "format": "short",
       "label": "Number of stale forward extremities in room"
      }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.75, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events_total > 0))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Number of state resolution performed, by number of state groups involved (heatmap)",
     "type": "heatmap",
     "description": "Colour reflects the number of state resolution operations performed over the given number of state groups, or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of state resolutions performed, by number of state groups involved (quantiles)",
     "type": "graph",
     "description": "For a given percentage P, the number X where P% of state resolution operations took place over X state groups or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short", "label": "Number of state groups" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.75, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.99, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Stale extremity dropping",
     "type": "graph",
     "description": "When we do a state res while persisting events we try and see if we can prune any stale extremities.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_state_resolutions_during_persistence_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "State res "
      },
      {
       "expr": "sum(rate(synapse_storage_events_potential_times_prune_extremities_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "Potential to prune"
      },
      {
       "expr": "sum(rate(synapse_storage_events_times_pruned_extremities_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "Pruned"
      }
     ]
    }
   ]
  },
  {
   "title": "MAU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MAU Limits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(synapse_admin_mau_max{instance=\"$instance\"})",
       "legendFormat": "Max"
      },
      {
       "expr": "max(synapse_admin_mau_current{instance=\"$instance\"})",
       "legendFormat": "Current"
      }
     ]
    },
    {
     "title": "MAU by Appservice",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_admin_mau_current_mau_by_service{instance=\"$instance\"}",
       "legendFormat": "{{ app_service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Notifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Notifier Streams Woken",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_notifier_users_woken_by_stream_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{stream}} {{index}}"
      }
     ]
    },
    {
     "title": "Presence Stream Fetch Type Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_get_updates_total{job=~\"$job\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Appservices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sent Events rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_appservice_api_sent_events_total{instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Transactions rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_appservice_api_sent_transactions_total{instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{exported_service }} {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Presence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Presence",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_notified_presence_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Notified"
      },
      {
       "expr": "rate(synapse_handler_presence_federation_presence_out_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Remote ping"
      },
      {
       "expr": "rate(synapse_handler_presence_presence_updates_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Total updates"
      },
      {
       "expr": "rate(synapse_handler_presence_federation_presence_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Remote updates"
      },
      {
       "expr": "rate(synapse_handler_presence_bump_active_time_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Bump active time"
      }
     ]
    },
    {
     "title": "Presence state transitions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_state_transition_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{from}} -> {{to}}"
      }
     ]
    },
    {
     "title": "Presence  notify reason",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_notify_reason_total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "External Cache Set Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(synapse_external_cache_set{job=~\"$job\", instance=\"$instance\", index=~\"$index\"}[$bucket_size])",
     "legendFormat": "{{ cache_name }} {{job}}-{{ index }}"
    }
   ]
  },
  {
   "title": "External Cache Get Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum without (hit) (rate(synapse_external_cache_get{job=~\"$job\", instance=\"$instance\", index=~\"$index\"}[$bucket_size]))",
     "legendFormat": "{{ cache_name }} {{job}}-{{ index }}"
    }
   ]
  },
  {
   "title": "External Cache Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(synapse_external_cache_response_time_seconds_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "External Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(synapse_external_cache_get{job=~\"$job\", instance=\"$instance\", index=~\"$index\", hit=\"False\"}[$bucket_size])",
     "legendFormat": "{{ cache_name }} {{job}}-{{ index }}"
    }
   ]
  }
 ]
}