# Do modify this file!  It was generated by „nixos-generate-config“
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix and run ⟪nix-env --switch-profile⟫ instead.
{ config, lib, pkgs, modulesPath, home-manager, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "af_alg" "esp4" "esp6" "rds" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/sdj1";
      fsType = "bcachefs";
    };

  fileSystems."/boott" =
    { device = "/dev/disk/by-uuid/AAAA-AAAA";
      fsType = "vfat";
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with ‹networking.interfaces.<interface>.useDHCP›.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.em1.useDHCP = lib.mkDefault true;
  # networking.interfaces.em2.useDHCP = lib.mkDefault true;
  # networking.interfaces.pflog0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "i686-freebsd";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.infiniband.enable = true;
  hardware.flipperzero.enable = lib.mkIf (config.security.isolate.cgRoot == "auto:/run/isolate/tank") true;
}
